title = "Jay Khabra - Full Stack Developer"
baseURL = ""
tags = ["web developer", "mohali web developer", "node developer", "javascript developer", "react developer", "python developer", "express developer", "web developer portfolio"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "jkhabra"

[Params]
  tagline = "Jay Khabra"
  author = "Toma Nistor"
  description = "Full-stack web developer and UI/UX enthusiast based in Mohali, Punjabi."
  logoBig = "/images/jay.png"
  logoSmall = "/images/jay.png"
  favicon = "/images/favicon.ico"
  opengraphImage = "/images/me.jpg"
  email = "jkhabra09@gmail.com"
  googleTagManger = ""
  customCSS = false

  # Social media links in footer
  twitter = "KhabraJay"
  linkedin = "jatinder-khabra-39070310a"
  github = "jkhabra"
  facebook = ""

  # Copyright and theme author credit in footer
  copyright = true
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = true
  ajaxFormspreeGold = false
  ajaxBasin = false

  # Lazy loading with lazysizes
  lazyloading = true

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Work"
  url  = "/#work"
  weight = 2
[[menu.main]]
  name = "Blog"
  url  = "/#blog"
  weight = 3
[[menu.main]]
  name = "Contact"
  url  = "/#contact"
  weight = 4